### PR TITLE
Content updates to 'what happens next' page

### PR DESCRIPTION
**Pull request by hannahkc**
Following usability testing in sprint 9 I have: 

- Made the label text more descriptive. And clearer that it is information for people completing the form.
- Added 'example' heading to make it clearer what the example is.

Also want to remove the character count but not sure how to do that so I need help!

### CODE REVIEW

**Review by christophercameron-ixd — APPROVED** [review]
Looks good to me.

Happy to help removing the character counter, but not sure it why :) 

Pretty sure it's just changing the macro name from "govukCharacterCount" to "govukTextarea" and removing the line `maxlength: 2000,`

Can talk through this if it's easier

**Comment by hannahkc** [comment]
Thanks Chris! Does "Happy to help removing the character counter, but not sure it why :)" mean you're not sure we should remove the character count?

**Comment by christophercameron-ixd** [comment]
Yeah, that's right. Seems like it was an issue as users were getting confused with the "Declaration" screen as they had switched hats (form creator to form filler) but it didn't come up as being an impact or noteworthy in the what happens next screen

**Comment by hannahkc** [comment]
So my thinking was that on the declaration page the character count appeared to give an expectation of amount of text you should provide. If it created that expectation from the declaration page, then there's a high risk they'd have it from this page too? 

I also am not sure what benefit the character count provides for users if it's such a high number and we actually don’t want more than a couple of lines (because they can’t format the text)?

Happy to leave it in though.

**Comment by christophercameron-ixd** [comment]
That's fair. I'm just not sure we've tested it enough either way, so I'm unsure what the best option is - I think the things we should consider or ask are is there a limit in the technical sense (if so what? and why?) and I would have hoped we'd keep the formatting as we discussed with Al the other week?

I have no commitment to it one way or the other though :)

**Comment by hannahkc** [comment]
Cool I'll merge as is then.

**Pull request merged**
