### PR TITLE
Migrate prototype to use v13 of the prototype kit

### PR DESCRIPTION
**Pull request by lfdebrux**
This PR updates our code to use GOV.UK Prototoype Kit version 13.4.0.

> Note that you know need to run the prototype using `npm run dev`

All custom functionality has been preserved, although some needed a little persuasion... see commit messages for details :sweat_smile:

Trello card: https://trello.com/c/pIh1dPWP

### CODE REVIEW

**Comment by christophercameron-ixd** [comment]
Looks like the heroku is no longer able to deploy this. Has something changed in the settings of the new version? 
Thinking about the config vars maybe? 

Currently:
NODE_ENV - production
PASSWORD - prototypes

**Comment by DavidBiddle** [comment]
@christophercameron-ixd I've just done a manual deploy to my personal heroku account with those details and it seems to have worked with those environment variables (https://test-forms-prototype-kit.herokuapp.com). Do you get anything back in the build log (Activity tab -> View build log)?

**Comment by christophercameron-ixd** [comment]
I get

`-----> Build
       
-----> Caching build
       - npm cache
       
-----> Pruning devDependencies
       npm notice 
       npm notice New minor version of npm available! 9.5.0 -> 9.6.1
       npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.6.1>
       npm notice Run `npm install -g npm@9.6.1` to update!
       npm notice 
       npm ERR! code ERR_INVALID_ARG_TYPE
       npm ERR! The "from" argument must be of type string. Received undefined
       
       npm ERR! A complete log of this run can be found in:
       npm ERR!     /tmp/npmcache.dVxvd/_logs/2023-03-13T08_41_27_141Z-debug-0.log
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - Node version not specified in package.json
         https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed`

**Comment by lfdebrux** [comment]
> I get
> 
> ```
> -----> Build
>        
> -----> Caching build
>        - npm cache
>        
> -----> Pruning devDependencies
>        npm notice 
>        npm notice New minor version of npm available! 9.5.0 -> 9.6.1
>        npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.6.1>
>        npm notice Run `npm install -g npm@9.6.1` to update!
>        npm notice 
>        npm ERR! code ERR_INVALID_ARG_TYPE
>        npm ERR! The "from" argument must be of type string. Received undefined
>        
>        npm ERR! A complete log of this run can be found in:
>        npm ERR!     /tmp/npmcache.dVxvd/_logs/2023-03-13T08_41_27_141Z-debug-0.log
>        ...

I can reproduce this error when running `npm install` with Node 18.15.0 and npm 9.5.0. Will investigate further.

**Review by christophercameron-ixd — APPROVED** [review]
All looks good to me, and is working on heroku! 

Would be good to know if the nunjucks-markdown was something we custom added and if so, why it wasn’t working anymore. Is this something that we should make the prototype-kit team aware of?

**Pull request merged**
